## This is test deployment for Kubernetes platforms.
## This is _not_ intended to be use in producction.
##
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-mariadb
  name: test-mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-mariadb
  template:
    metadata:
      labels:
        app: test-mariadb
    spec:
      containers:
      - image: bitnami/mariadb
        name: test-mariadb
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes" 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-mariadb
  name: test-mariadb
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: test-mariadb
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-redis
  name: test-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-redis
  template:
    metadata:
      labels:
        app: test-redis
    spec:
      containers:
      - image: bitnami/redis
        name: test-redis
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes" 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-redis
  name: test-redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: test-redis
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-mongodb
  name: test-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-mongodb
  template:
    metadata:
      labels:
        app: test-mongodb
    spec:
      containers:
      - image: bitnami/mongodb
        name: test-mongodb
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-mongodb
  name: test-mongodb
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: test-mongodb
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-dreamfactory
  name: test-dreamfactory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-dreamfactory
  template:
    metadata:
      labels:
        app: test-dreamfactory
    spec:
      containers:
      - image: bitnami/dreamfactory
        name: test-dreamfactory
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes" 
        - name: MARIADB_HOST
          value: test-mariadb
        - name: MARIADB_PORT_NUMBER
          value: "3306"
        - name: MONGODB_HOST
          value: test-mongodb
        - name: MONGODB_PORT_NUMBER
          value: "27017"
        - name: REDIS_HOST
          value: test-redis
        - name: REDIS_PORT_NUMBER
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-dreamfactory
  name: test-dreamfactory
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: test-dreamfactory
  sessionAffinity: None
  type: ClusterIP
